version: "3"

services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - .:/api
  
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - .:/frontend
    depends_on:
      - api
    