"""create attribute url_image

Revision ID: 8020aafdf40b
Revises: 5f35eed1a724
Create Date: 2023-04-29 19:41:33.888865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8020aafdf40b'
down_revision = '5f35eed1a724'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('url_image', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'url_image')
    # ### end Alembic commands ###
